language: node_js
node_js:
- '10'
deploy:
  provider: s3
  access_key_id: AKIARRT74VEDFMGTFYSA
  secret_access_key:
    secure: rkq0BZIGpLNTxvRMRfB1zyqB+au4Nkj3rYkasP4ecoRH2JU9tmGMAFs3vDh+S6H2/hnBULqiROxI71nLyZVJwArDnvs2SHsA/M4u5J2qOnnvue0iVFm4o9rndmf0FKIT0b2kRFhNBySj08LFLSrO1EdBaYpQiHbM/hNlN4kLDq8lK/rxQLc1J/MMWdjbFD/GFX6y6q8xEzuqxQlxyGtDCK5uqamwHLMELW/vmw44Q+5yvuZ6ZAsbAzz2A4Qjv4wd6hmfiqHhXxUUcB2FfchyLhAjhjHQZD7KFK0YvXBTq8bAg+yglcPw+23vI5jEQ+EYtxKbL+ipuZ+UvfeVv5SErkq6gDUnHl2EWwJMtBw6n2IeXOsfmmkyE14+G0GGnriYuUkaOmiYcl+Q4FFbVKkx6pYJinBa3kWfcdQ1Hvi0zP68aH1jUhgWxNtNF9WLNWyub1E5f/mPBHMRxriZcKhWftlVn1fXiM0KNoYtRQ2PXP/hy/atvxml6gS2aCz2WY2GVKrCxRNtzUkrX1fxErDlA+KqU8sC0e265yAp3KaZHIvVaQ4QtJEoaJALGOtYFA1IQouf7Q2k8Y8AZz6MkykqcBX6UPnJw1bzoyNxHK04kkytU0nlgRAcBlKoHxadmyipL8Pff9cpUUeMK18tgKrDPswfL3FcoEaYZ+Sq3wYws/o=
  bucket: vanbujm-aws-terraform-bucket
  acl: 'public_read'
  skip_cleanup: true
  on:
    repo: vanbujm/aws-terraform
